- type: entity
  id: BaseBone
  parent: BaseItem
  abstract: true
  components:
  - type: Sprite
    sprite: Mobs/Species/Skeleton/parts.rsi
  - type: Organ
  - type: Food
  - type: Openable
    openableByHand: false
    sound:
      path: /Audio/_Starlight/Items/Bones/bonebreak.ogg
    examineText: bone-examine-open
    closedPopup: bone-examine-closed
    closeable: false
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 50
      behaviors:
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
    - trigger:
        !type:DamageTrigger
        damage: 20
      behaviors:
      - !type:SpawnEntitiesBehavior
        spawn:
          MaterialBones1:
            min: 1
            max: 2
      - !type:PlaySoundBehavior
        sound:
          path: /Audio/_Starlight/Items/Bones/bonebreak.ogg
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
    - trigger:
        !type:DamageTrigger
        damage: 6
      behaviors:
      - !type:OpenBehavior
      - !type:PlaySoundBehavior
        sound:
          path: /Audio/_Starlight/Items/Bones/bonebreak.ogg
  - type: DamageOnLand
    damage:
      types:
        Blunt: 3
  - type: DamageOtherOnHit
    damage:
      types:
        Blunt: 3
  - type: Gibbable
  - type: Extractable
    grindableSolutionName: organ
  - type: Damageable
    damageContainer: Biological
  - type: SolutionContainerManager
    solutions:
      organ:
        reagents:
        - ReagentId: Nutriment
          Quantity: 15
      food:
        maxVol: 10
        reagents:
        - ReagentId: UncookedAnimalProteins
          Quantity: 5
        - ReagentId: Fat
          Quantity: 5
  - type: FlavorProfile
    flavors:
      - people
      - boney
  - type: Tag
    tags:
      - Meat

- type: entity
  id: BaseBoneSkull
  parent: BaseBone
  name: "a skull"
  abstract: true
  components:
    - type: Sprite
      sprite: Mobs/Species/Skeleton/parts.rsi
      state: "head_m"
    - type: Icon
      sprite: Mobs/Species/Skeleton/parts.rsi
      state: "head_m"

- type: entity
  id: BaseBoneRibcage
  parent: BaseBone
  name: "a ribcage"
  abstract: true
  components:
    - type: Sprite
      sprite: Mobs/Species/Skeleton/parts.rsi
      state: "torso_f"
    - type: Icon
      sprite: Mobs/Species/Skeleton/parts.rsi
      state: "torso_f"

- type: entity
  id: BaseBoneHip
  parent: BaseBone
  name: "a hipbone"
  abstract: true
  components:
    - type: Sprite
      sprite: Mobs/Species/Skeleton/parts.rsi
      state: "torso_m"
    - type: Icon
      sprite: Mobs/Species/Skeleton/parts.rsi
      state: "torso_m"

- type: entity
  id: BaseBoneLeftArm
  parent: BaseBone
  name: "bones from a left arm"
  abstract: true
  components:
    - type: Sprite
      sprite: Mobs/Species/Skeleton/parts.rsi
      state: "l_arm"
    - type: Icon
      sprite: Mobs/Species/Skeleton/parts.rsi
      state: "l_arm"

- type: entity
  id: BaseBoneRightArm
  parent: BaseBone
  name: "bones from a right arm"
  abstract: true
  components:
    - type: Sprite
      sprite: Mobs/Species/Skeleton/parts.rsi
      state: "r_arm"
    - type: Icon
      sprite: Mobs/Species/Skeleton/parts.rsi
      state: "r_arm"

- type: entity
  id: BaseBoneRightHand
  parent: BaseBone
  name: "bones from a right hand"
  abstract: true
  components:
    - type: Sprite
      sprite: Mobs/Species/Skeleton/parts.rsi
      state: "r_hand"
    - type: Icon
      sprite: Mobs/Species/Skeleton/parts.rsi
      state: "r_hand"

- type: entity
  id: BaseBoneLeftHand
  parent: BaseBone
  name: "bones from a left hand"
  abstract: true
  components:
    - type: Sprite
      sprite: Mobs/Species/Skeleton/parts.rsi
      state: "l_hand"
    - type: Icon
      sprite: Mobs/Species/Skeleton/parts.rsi
      state: "l_hand"

- type: entity
  id: BaseBoneLeftLeg
  parent: BaseBone
  name: "bones from a left leg"
  abstract: true
  components:
    - type: Sprite
      sprite: Mobs/Species/Skeleton/parts.rsi
      state: "l_leg"
    - type: Icon
      sprite: Mobs/Species/Skeleton/parts.rsi
      state: "l_leg"

- type: entity
  id: BaseBoneRightLeg
  parent: BaseBone
  name: "bones from a right leg"
  abstract: true
  components:
    - type: Sprite
      sprite: Mobs/Species/Skeleton/parts.rsi
      state: "r_leg"
    - type: Icon
      sprite: Mobs/Species/Skeleton/parts.rsi
      state: "r_leg"

- type: entity
  id: BaseBoneRightFoot
  parent: BaseBone
  name: "bones from a right foot"
  abstract: true
  components:
    - type: Sprite
      sprite: Mobs/Species/Skeleton/parts.rsi
      state: "r_foot"
    - type: Icon
      sprite: Mobs/Species/Skeleton/parts.rsi
      state: "r_foot"

- type: entity
  id: BaseBoneLeftFoot
  parent: BaseBone
  name: "bones from a left foot"
  abstract: true
  components:
    - type: Sprite
      sprite: Mobs/Species/Skeleton/parts.rsi
      state: "l_foot"
    - type: Icon
      sprite: Mobs/Species/Skeleton/parts.rsi
      state: "l_foot"